### ISSUE TITLE
OpenCV error while deepfrying

### ISSUE THREAD

**Issue by ksdfg** [ksdfg/neko-chan-telebot#7]
https://github.com/ksdfg/neko-chan-telebot/commit/25309cc7c73484572e36430f947e2e54040e3e3d#diff-ff094f2fa9345ba309873d69c91c0fa1R184

Whenever this line runs I get the following error -

```
An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/home/ksdfg/stuff/code/neko-chan-telebot/venv/lib/python3.8/site-packages/telegram/utils/promise.py", line 56, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/home/ksdfg/stuff/code/neko-chan-telebot/telebot/modules/memes.py", line 214, in fry
    loop.run_until_complete(_fry(Image.open("sticker.png"), update.effective_message.reply_to_message, file))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ksdfg/stuff/code/neko-chan-telebot/telebot/modules/memes.py", line 185, in _fry
    image = await deepfry(img=image, flares=True)
  File "/home/ksdfg/stuff/code/neko-chan-telebot/venv/lib/python3.8/site-packages/deeppyer/__init__.py", line 54, in deepfry
    faces = face_cascade.detectMultiScale(
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-6179nsls/opencv/modules/objdetect/src/cascadedetect.cpp:1689: error: (-215:Assertion failed) !empty() in function 'detectMultiScale'
```

**Comment by ksdfg** [comment]
ummm, can someone check this btw?

**Comment by akhilnarang** [comment]
@ksdfg https://t.me/c/1488239470/61959

**Comment by ksdfg** [comment]
[Found answer](https://github.com/Ovyerus/deeppyer/issues/5#issuecomment-711369925), but seems like the flare design has changed. Not worth it imo, but if I get a better answer then I'll imporve it. For now just going to merge code in without flares.
